# .circleci/config.yml
version: 2.1
workflows:
  commit:
    jobs:
      - build
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: go test -v ./...
      - run: go build
  release:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

